runtime: go116

instance_class: F1

env_variables:
  PROJECT_NAME: ${PROJECT_NAME}
  SESSION_COLLECTION: ${SESSION_COLLECTION}
  SMTP_HOST: ${SMTP_HOST}
  SMTP_PORT: ${SMTP_PORT}
  SMTP_USER: ${SMTP_USER}
  SMTP_PASS: ${SMTP_PASS}
