# This is a basic workflow to help you get started with Actions

name: AppEngine Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AppEnging

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_NAME }}

      - name: Prepare app.yaml
        run: envsubst < app.yaml.tpl > app.yaml

      - name: Deploy to App Engine
        run: gcloud app deploy --quiet