# This is a basic workflow to help you get started with Actions

name: AppEngine Deployment

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Tests"]
    branches: [ main ]
    types: 
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: AppEnging
    env:
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        SESSION_COLLECTION: ${{ secrets.SESSION_COLLECTION }}
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_NAME }}

      - name: Prepare app.yaml
        run: envsubst < app.yaml.tpl > app.yaml

      - name: Deploy to App Engine
        run: gcloud app deploy --quiet